name: Convert Apple Cert to P12

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create private key
        run: echo "${{ secrets.APPLE_SIGNING_KEY }}" > ios_signing.key

      - name: Decode Apple certificate
        run: echo "${{ secrets.APPLE_CERT_BASE64 }}" | base64 -d > ios_cert.cer

      - name: Convert CER to PEM
        run: openssl x509 -in ios_cert.cer -inform DER -out ios_cert.pem -outform PEM

      - name: Export P12
        run: |
          openssl pkcs12 -export \
            -inkey ios_signing.key \
            -in ios_cert.pem \
            -out ios_cert.p12 \
            -password pass:${{ secrets.P12_PASSWORD }}

      - name: Upload P12
        uses: actions/upload-artifact@v4
        with:
          name: ios-p12
          path: ios_cert.p12
