name: Convert Apple Cert to P12

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo (optional if you need files from repo)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Create the private key from secret
      - name: Create iOS signing key
        run: |
          echo "${{ secrets.APPLE_SIGNING_KEY }}" > ios_signing.key

      # 3. Decode Apple certificate from Base64 secret
      - name: Decode Apple certificate
        run: |
          echo "${{ secrets.APPLE_CERT_BASE64 }}" | base64 -d > ios_cert.cer

      # 4. Convert certificate to PEM
      - name: Convert CER to PEM
        run: |
          openssl x509 -in ios_cert.cer -inform DER -out ios_cert.pem -outform PEM

      # 5. Export to P12 using the private key
      - name: Export P12
        run: |
          openssl pkcs12 -export \
            -inkey ios_signing.key \
            -in ios_cert.pem \
            -out ios_cert.p12 \
            -password pass:${{ secrets.P12_PASSWORD }}

      # 6. Upload P12 as artifact
      - name: Upload P12
        uses: actions/upload-artifact@v4
        with:
          name: ios-p12
          path: ios_cert.p12
