name: Convert Apple Cert to P12

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 1: Save private key from secret
      - name: Save private key
        run: |
          echo "${{ secrets.APPLE_SIGNING_KEY }}" > ios_signing.key

      # Step 2: Decode Apple certificate
      - name: Decode Apple certificate
        run: |
          echo "${{ secrets.APPLE_CERT_BASE64 }}" | base64 -d > ios_cert.cer

      # Step 3: Convert .cer to .pem
      - name: Convert to PEM
        run: |
          openssl x509 -in ios_cert.cer -inform DER -out ios_cert.pem -outform PEM

      # Step 4: Convert to .p12
      - name: Convert to P12
        run: |
          openssl pkcs12 -export \
            -inkey ios_signing.key \
            -in ios_cert.pem \
            -out ios_cert.p12 \
            -password pass:${{ secrets.P12_PASSWORD }}

      # Step 5: Upload the P12 for next workflow (optional)
      - name: Upload P12
        uses: actions/upload-artifact@v4
        with:
          name: ios-p12
          path: ios_cert.p12
