name: Build & Sign iOS App

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Save private key
      - name: Save Signing Key
        run: echo "${{ secrets.APPLE_SIGNING_KEY }}" > ios_signing.key

      # 2. Save Apple Certificate
      - name: Save Apple Certificate
        run: echo "${{ secrets.APPLE_CERT_BASE64 }}" | base64 -d > ios_cert.cer

      # 3. Convert .cer to .pem (optional)
      - name: Convert CER to PEM
        run: openssl x509 -in ios_cert.cer -inform DER -out ios_cert.pem -outform PEM

      # 4. Export .p12 **on macOS**
      - name: Export P12
        run: |
          openssl pkcs12 -export \
            -inkey ios_signing.key \
            -in ios_cert.pem \
            -out ios_cert.p12 \
            -password pass:Infy17cre@t

      # 5. Install certificate
      - name: Install Certificate
        run: |
          security create-keychain -p "" build.keychain
          security import ios_cert.p12 -k ~/Library/Keychains/build.keychain -P "Infy17cre@t" -T /usr/bin/codesign
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "" ~/Library/Keychains/build.keychain

      # 6. Save Provisioning Profile
      - name: Add Provisioning Profile
        run: |
          echo "${{ secrets.APPLE_PROVISION_PROFILE }}" | base64 -d > managerXApp.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp managerXApp.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      # 7. Setup Node and dependencies
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install --legacy-peer-deps

      # 8. Build Ionic Capacitor iOS app
      - run: |
          npm run build
          npx cap sync ios
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release archive -archivePath $PWD/build/App.xcarchive

      # 9. Export IPA
      - run: |
          xcodebuild -exportArchive \
            -archivePath ios/App/build/App.xcarchive \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -exportPath ios/App/output

      # 10. Upload IPA
      - uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ios/App/output/*.ipa
