jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Ionic iOS
        run: |
          npm run build
          npx cap sync ios

      - name: Install CocoaPods
        run: |
          cd ios/App
          pod install

      - name: Setup Ruby & Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Install Fastlane
        run: gem install fastlane -v 2.228.0

      # Decode API Key (from base64 secret if needed)
      - name: Save AuthKey.p8
        run: |
          echo "${{ secrets.APP_STORE_CONNECT_API_KEY_BASE64 }}" | base64 --decode > AuthKey.p8

      # Authenticate with App Store Connect
      - name: Authenticate with App Store Connect
        run: |
          fastlane run app_store_connect_api_key \
            key_id:"${{ secrets.APP_STORE_CONNECT_KEY_ID }}" \
            issuer_id:"${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}" \
            key_filepath:"AuthKey.p8"

      # Detect workspace
      - name: Detect Workspace
        run: |
          WORKSPACE=$(find ios/App -maxdepth 1 -name "*.xcworkspace" -type d | head -n 1)
          echo "Workspace detected: $WORKSPACE"
          echo "WORKSPACE=$WORKSPACE" >> $GITHUB_ENV

      # Build with Fastlane
      - name: Build iOS App
        run: |
          fastlane run build_ios_app \
            workspace:"$WORKSPACE" \
            scheme:"App" \
            export_method:"app-store"

      # Upload IPA artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: iOS-IPA
          path: ios/App/output/*.ipa
