name: Build & Sign iOS App New

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Install npm dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 4️⃣ Patch PrimeNG for Angular 20
      - name: Patch PrimeNG
        run: |
          sed -i '' 's/, InjectFlags//' node_modules/primeng/dynamicdialog/dynamicdialog-injector.d.ts
          sed -i '' 's/| InjectFlags//g' node_modules/primeng/dynamicdialog/dynamicdialog-injector.d.ts

      # 5️⃣ Decode & install certificates & provisioning profile
      - name: Install Certificates & Provisioning Profile
        run: |
          # Decode .p12 certificate
          echo "$IOS_CERT_BASE64" | base64 --decode > ios-cert.p12

          # Decode provisioning profile
          echo "$IOS_PROV_PROFILE_BASE64" | base64 --decode > ios-profile.mobileprovision

          # Create a keychain for signing
          security create-keychain -p "" build.keychain
          security import ios-cert.p12 -k ~/Library/Keychains/build.keychain -P "" -T /usr/bin/codesign
          security list-keychains -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain

          # Install provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ios-profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
        env:
          IOS_CERT_BASE64: ${{ secrets.IOS_CERT_BASE64 }}
          IOS_PROV_PROFILE_BASE64: ${{ secrets.IOS_PROV_PROFILE_BASE64 }}

      # 6️⃣ Build Ionic iOS App
      - name: Build Ionic iOS App
        run: |
          npm run build
          npx cap sync ios

      # 7️⃣ Archive iOS App
      - name: Archive iOS App
        run: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $PWD/build/App.xcarchive \
            DEVELOPMENT_TEAM=NPXC63W394 \
            PROVISIONING_PROFILE_SPECIFIER="managerXApp" \
            CODE_SIGN_STYLE=Manual \
            clean archive

      # 8️⃣ Export signed IPA
      - name: Export IPA
        run: |
          cd ios/App
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath output

      # 9️⃣ Upload IPA artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ios/App/output/*.ipa
