name: Build & Sign iOS App New

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install npm dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 4. Patch PrimeNG for Angular 20
      - name: Patch PrimeNG
        run: |
          sed -i '' 's/, InjectFlags//' node_modules/primeng/dynamicdialog/dynamicdialog-injector.d.ts
          sed -i '' 's/| InjectFlags//g' node_modules/primeng/dynamicdialog/dynamicdialog-injector.d.ts

      # 5. Setup Ruby & Fastlane
      - name: Setup Ruby & Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      # 6. Decrypt certificates using Match
      - name: Match App Store Certificates
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          bundle exec fastlane match appstore \
            --git_url https://github.com/Rashmal/managerXApp.git \
            --app_identifier com.yourcompany.managerXApp \
            --team_id NPXC63W394 \
            --verbose

      # 7. Build Ionic Capacitor iOS
      - name: Build Ionic iOS App
        run: |
          npm run build
          npx cap sync ios

      # 8. Archive with Xcode (manual signing, team ID hardcoded)
      - name: Archive iOS App
        run: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $PWD/build/App.xcarchive \
            DEVELOPMENT_TEAM=NPXC63W394 \
            PROVISIONING_PROFILE_SPECIFIER="managerXApp" \
            CODE_SIGN_STYLE=Manual \
            clean archive

      # 9. Export signed IPA
      - name: Export IPA
        run: |
          cd ios/App
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath output

      # 10. Upload IPA artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ios/App/output/*.ipa
