name: Build & Sign iOS App fastlane

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install npm dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 4. Patch PrimeNG dynamicdialog-injector for Angular 20
      - name: Patch PrimeNG
        run: |
          sed -i '' 's/, InjectFlags//' node_modules/primeng/dynamicdialog/dynamicdialog-injector.d.ts
          sed -i '' 's/| InjectFlags//g' node_modules/primeng/dynamicdialog/dynamicdialog-injector.d.ts

      # 5. Setup Fastlane
      - name: Install Fastlane
        run: gem install fastlane

      # 6. Match (fetch certificates & profiles)
      - name: Fastlane Match (App Store)
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          FASTLANE_TEAM_ID: NPXC63W394
        run: |
          fastlane match appstore --readonly --git_url https://github.com/Rashmal/managerXApp.git

      # 7. Build Ionic Capacitor iOS
      - name: Build Ionic iOS App
        run: |
          npm run build
          npx cap sync ios

      # 8. Archive with Xcode using automatic signing from Match
      - name: Archive iOS App
        run: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $PWD/build/App.xcarchive \
            clean archive \
            -allowProvisioningUpdates

      # 9. Export signed IPA
      - name: Export IPA
        run: |
          cd ios/App
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath output \
            -allowProvisioningUpdates

      # 10. Upload IPA artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ios/App/output/*.ipa
