name: Build & Sign iOS App

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    env:
      APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
      APP_SCHEME: ${{ secrets.APP_SCHEME }}
      APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }}

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install npm dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 4. Patch PrimeNG if Angular 20 (optional)
      - name: Patch PrimeNG
        run: |
          sed -i '' 's/, InjectFlags//' node_modules/primeng/dynamicdialog/dynamicdialog-injector.d.ts
          sed -i '' 's/| InjectFlags//g' node_modules/primeng/dynamicdialog/dynamicdialog-injector.d.ts

      # 5. Build Ionic project for iOS
      - name: Build Ionic iOS
        run: |
          npm run build
          npx cap sync ios

      # 6. Install fastlane
      - name: Install Fastlane
        run: sudo gem install fastlane

      # 7. Match / Generate certificates & provisioning profiles via App Store Connect API
      - name: Generate signing credentials
        run: |
          echo "$APP_STORE_CONNECT_KEY" > AuthKey.p8
          fastlane match development \
            --type ios \
            --readonly false \
            --app_identifier $APP_IDENTIFIER \
            --username YOUR_APPLE_ID_EMAIL \
            --api_key_path AuthKey.p8 \
            --api_key_id $APP_STORE_CONNECT_KEY_ID \
            --api_issuer_id $APP_STORE_CONNECT_ISSUER_ID
          fastlane match appstore \
            --type ios \
            --readonly false \
            --app_identifier $APP_IDENTIFIER \
            --username YOUR_APPLE_ID_EMAIL \
            --api_key_path AuthKey.p8 \
            --api_key_id $APP_STORE_CONNECT_KEY_ID \
            --api_issuer_id $APP_STORE_CONNECT_ISSUER_ID

      # 8. Build and archive with Xcode
      - name: Build with Xcode
        run: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
                     -scheme $APP_SCHEME \
                     -sdk iphoneos \
                     -configuration Release \
                     archive -archivePath $PWD/build/App.xcarchive

      # 9. Export IPA
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
                     -archivePath ios/App/build/App.xcarchive \
                     -exportOptionsPlist ios/App/exportOptions.plist \
                     -exportPath output

      # 10. Upload IPA artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: iOS-IPA
          path: output/*.ipa
