name: Build & Sign iOS App

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Patch PrimeNG
        run: |
          sed -i '' 's/, InjectFlags//' node_modules/primeng/dynamicdialog/dynamicdialog-injector.d.ts
          sed -i '' 's/| InjectFlags//g' node_modules/primeng/dynamicdialog/dynamicdialog-injector.d.ts

      - name: Add Provisioning Profile
        run: |
          echo "${{ secrets.APPLE_PROVISION_PROFILE }}" | base64 -d > managerXApp.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp managerXApp.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      # Save the P12 certificate directly (no CER -> PEM -> P12)
      - name: Save Apple P12 Certificate
        run: |
          echo "${{ secrets.APPLE_P12_BASE64 }}" | base64 -d > ios_cert.p12

      - name: Install Certificate in Keychain
        run: |
          security create-keychain -p "" build.keychain
          security import ios_cert.p12 \
            -k ~/Library/Keychains/build.keychain \
            -P "${{ secrets.APPLE_CERT_PASSWORD }}" \
            -T /usr/bin/codesign \
            -T /usr/bin/security
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "" ~/Library/Keychains/build.keychain

      - name: Install Fastlane
        run: sudo gem install fastlane -v 2.228.0

      - name: Build Ionic iOS App
        run: |
          npm run build
          npx cap sync ios

      - name: Archive iOS App
        run: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $PWD/build/App.xcarchive \
            DEVELOPMENT_TEAM=NPXC63W394 \
            PROVISIONING_PROFILE_SPECIFIER="ManagerXApp" \
            CODE_SIGN_STYLE=Manual \
            clean archive

      - name: Export IPA
        run: |
          cd ios/App
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath output

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ios/App/output/*.ipa
