name: Build & Sign iOS App

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install npm dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 4. Patch PrimeNG (if needed)
      - name: Patch PrimeNG
        run: |
          sed -i '' 's/, InjectFlags//' node_modules/primeng/dynamicdialog/dynamicdialog-injector.d.ts || true
          sed -i '' 's/| InjectFlags//g' node_modules/primeng/dynamicdialog/dynamicdialog-injector.d.ts || true

      # 5. Build Ionic and sync iOS
      - name: Build Ionic iOS
        run: |
          npm run build
          npx cap sync ios

      # 6. Install CocoaPods and generate valid workspace
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios/App
          pod repo update
          pod install --verbose

      # 7. Detect actual .xcworkspace
      - name: Detect workspace
        run: |
          WORKSPACE=$(find ios/App -maxdepth 1 -name "*.xcworkspace" -type d | head -n 1)
          if [ -z "$WORKSPACE" ]; then
            echo "Error: .xcworkspace not found"
            exit 1
          fi
          echo "Workspace detected: $WORKSPACE"
          echo "WORKSPACE=$WORKSPACE" >> $GITHUB_ENV

      # 8. Verify workspace has the correct scheme
      - name: Verify workspace scheme
        run: |
          cd ios/App
          SCHEME="${{ secrets.APP_SCHEME }}"
          if ! xcodebuild -list -workspace "$(basename $WORKSPACE)" | grep -q "$SCHEME"; then
            echo "Error: Scheme '$SCHEME' not found in workspace"
            exit 1
          fi
          echo "Scheme '$SCHEME' verified"

      # 9. Setup Ruby & Fastlane
      - name: Setup Ruby & Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Install Fastlane
        run: gem install fastlane -v 2.228.0

      # 10. Setup App Store Connect API key
      - name: Setup API Key
        run: echo "${{ secrets.APP_STORE_CONNECT_KEY }}" > AuthKey.p8
        env:
          APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }}

      # 11. Build & sign iOS
      - name: Build & Sign iOS
        run: |
          fastlane run build_ios_app \
            workspace: "$WORKSPACE" \
            scheme: "${{ secrets.APP_SCHEME }}" \
            export_method: "app-store" \
            api_key_path: "AuthKey.p8"

      # 12. Upload IPA artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: iOS-IPA
          path: ios/App/output/*.ipa
