name: Convert Apple Certificate

on:
  workflow_dispatch:

jobs:
  convert-cert:
    runs-on: ubuntu-latest

    steps:
      - name: Download private key
        uses: actions/download-artifact@v4
        with:
          name: ios-csr

      - name: Add Apple certificate
        run: |
          echo "${{ secrets.APPLE_CERT_BASE64 }}" | base64 -d > ios_cert.cer

      - name: Convert to .p12
        run: |
          openssl x509 -in ios_cert.cer -inform DER -out ios_cert.pem -outform PEM
          openssl pkcs12 -export -inkey ios_signing.key -in ios_cert.pem -out ios_cert.p12 -password pass:${{ secrets.P12_PASSWORD }}

      - name: Upload .p12
        uses: actions/upload-artifact@v4
        with:
          name: ios-p12
          path: ios_cert.p12
